src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\Table;
use Doctrine\ORM\Mapping\UniqueConstraint;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\EquatableInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity("email")
 * @UniqueEntity("name")
 * @Table(uniqueConstraints={
 *     @UniqueConstraint(name="email_unique",columns={"email"}),
 *     @UniqueConstraint(name="name_unique",columns={"name"})
 * })
 */
class User implements UserInterface, EquatableInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=16)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=190)
     */
    private $email;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $pass;

    /**
     * @ORM\Column(type="boolean")
     */
    private $validated;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\UserPendingValidation", mappedBy="user", cascade={"persist", "remove"})
     */
    private $pendingValidation;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Citizen", mappedBy="user")
     */
    private $citizens;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\AdminBan", mappedBy="user")
     */
    private $bannings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\FoundRolePlayText", mappedBy="user")
     */
    private $foundTexts;

    /**
     * @ORM\Column(type="integer")
     */
    private $soulPoints;
    
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Picto", mappedBy="user")
     */
    private $pictos;

    /**
     * @ORM\Column(type="string", length=32)
     */
    private $externalId = '';

    /**
     * @ORM\Column(type="boolean")
     */
    private $isAdmin = 0;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Avatar", cascade={"persist", "remove"})
     */
    private $avatar;

    /**
     * @ORM\Column(type="boolean")
     */
    private $preferSmallAvatars = false;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $postAsDefault;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $language = "de";

    public function __construct()
    {
        $this->citizens = new ArrayCollection();
        $this->foundTexts = new ArrayCollection();
        $this->pictos = new ArrayCollection();
        $this->bannings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getSalt( ): string {
        return 'user_salt_myhordes_ffee45';
    }

    /**
     * @return Collection|AdminBan[]
     */
    public function getBannings(): Collection
    {
        return $this->bannings;
    }

    public function getValidated(): ?bool
    {
        return $this->validated;
    }

    public function setValidated(bool $validated): self
    {
        $this->validated = $validated;

        return $this;
    }

    public function getPendingValidation(): ?UserPendingValidation
    {
        return $this->pendingValidation;
    }

    public function setPendingValidation(?UserPendingValidation $pendingValidation): self
    {
        $this->pendingValidation = $pendingValidation;

        // set (or unset) the owning side of the relation if necessary
        $newUser = null === $pendingValidation ? null : $this;
        if ($pendingValidation && $pendingValidation->getUser() !== $newUser) {
            $pendingValidation->setUser($newUser);
        }

        return $this;
    }

    /**
     * @inheritDoc
     */
    public function getRoles()
    {
        $roles = [];
        if ($this->pass === null) return $roles;
        if ($this->isAdmin) $roles[] = 'ROLE_ADMIN';
        if (strstr($this->email, "@localhost") === "@localhost") $roles[] = 'ROLE_DUMMY';        
        if ($this->validated) $roles[] = 'ROLE_USER';
        else $roles[] = 'ROLE_REGISTERED';
        if ($this->getIsBanned()) $roles[] = 'ROLE_BANNED';        
        return $roles;
    }

    /**
     * @inheritDoc
     */
    public function getPassword()
    {
        return $this->pass;
    }

    public function setPassword(?string $pass): self {
        $this->pass = $pass;
        return $this;
    }

    /**
     * @inheritDoc
     */
    public function eraseCredentials() {}

    /**
     * @inheritDoc
     */
    public function isEqualTo(UserInterface $user) {
        $b1 = $this->getPassword() !== null && $user->getPassword() !== null &&
            $this->getUsername() === $user->getUsername() &&
            $this->getPassword() === $user->getPassword() &&
            $this->getRoles() === $user->getRoles();
        if ($user instanceof User) {
            return $b1 &&
                $this->getIsAdmin() === $user->getIsAdmin();
        } else return $b1;
    }

    public function getIsBanned(): bool {
        foreach ($this->getBannings() as $b)
            if ($b->getActive())
                return true;
        return false;
    }

    public function getLongestActiveBan(): ?AdminBan {
        $ban = null;
        foreach ($this->getBannings() as $b){
            if ($b->getActive()) {
                if (!isset($ban)) {
                    $ban = $b;                       
                }
                else if ($b->getBanEnd() > $ban->getBanEnd())
                    $ban = $b;     
            }
        }            
        if (isset($ban))
            return $ban;
        return null;
    }

    /**
     * @return Collection|AdminBan[]
     */
    public function getActiveBans(): Collection {
        $bans = $this->getBannings();
        foreach ($bans as $ban){
                if (!($ban->getActive()))
                    $bans->remove($ban->getId());  
            }            
        return $bans;
    }

    public function getActiveCitizen(): ?Citizen {
        foreach ($this->getCitizens() as $c)
            if ($c->getActive())
                return $c;
        return null;
    }

    public function getAliveCitizen(): ?Citizen {
        foreach ($this->getCitizens() as $c)
            if ($c->getAlive())
                return $c;
        return null;
    }

    /**
     * @return Collection|Citizen[]
     */
    public function getCitizens(): Collection
    {
        return $this->citizens;
    }

    public function addCitizen(Citizen $citizen): self
    {
        if (!$this->citizens->contains($citizen)) {
            $this->citizens[] = $citizen;
            $citizen->setUser($this);
        }

        return $this;
    }

    public function removeCitizen(Citizen $citizen): self
    {
        if ($this->citizens->contains($citizen)) {
            $this->citizens->removeElement($citizen);
            // set the owning side to null (unless already changed)
            if ($citizen->getUser() === $this) {
                $citizen->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|RolePlayText[]
     */
    public function getFoundTexts(): Collection
    {
        return $this->foundTexts;
    }

    public function addFoundText(RolePlayText $foundText): self
    {
        if (!$this->foundTexts->contains($foundText)) {
            $this->foundTexts[] = $foundText;
        }

        return $this;
    }

    public function removeFoundText(RolePlayText $foundText): self
    {
        if ($this->foundTexts->contains($foundText)) {
            $this->foundTexts->removeElement($foundText);
        }

        return $this;
    }

    public function getSoulPoints(): ?int
    {
        return $this->soulPoints;
    }

    public function setSoulPoints(int $soulPoints): self
    {
        $this->soulPoints = $soulPoints;

        return $this;
    }

    public function addSoulPoints(int $soulPoints): self
    {
        $this->soulPoints += $soulPoints;

        return $this;
    }


    public function getExternalId(): ?string
    {
        return $this->externalId;
    }

    public function setExternalId(string $externalId): self
    {
        $this->externalId = $externalId;

        return $this;
    }

    /**
     * @return Collection|Pictos[]
     */
    public function getPictos(): Collection
    {
        return $this->pictos;
    }

    public function addPicto(Picto $picto): self
    {
        if (!$this->pictos->contains($picto)) {
            $this->pictos[] = $picto;
            $picto->setUser($this);
        }

        return $this;
    }

    public function removePicto(Picto $picto): self
    {
        if ($this->pictos->contains($picto)) {
            $this->pictos->removeElement($picto);
            // set the owning side to null (unless already changed)
            if ($picto->getUser() === $this) {
                $picto->setUser(null);
            }
        }

        return $this;
    }

    public function getIsAdmin(): ?bool
    {
        return $this->isAdmin;
    }

    public function setIsAdmin(bool $isAdmin): self
    {
        $this->isAdmin = $isAdmin;

        return $this;
    }

    public function getAvatar(): ?Avatar
    {
        return $this->avatar;
    }

    public function setAvatar(?Avatar $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

templates/ajax/soul/me.html.twig
{% extends "ajax/soul/shell.html.twig" %}
{% block soul_content %}
    <div class="row">
        <div class="cell rw-5 rw-sm-12 distinctions">
            <div class="distinctions-head center">
                {{ 'Statistiken'|trans({}, 'global') }}
            </div>
            <div class="distinctions-list center">
                <div class="overall">
                    {{ '%points% Punkte'|trans({'%points%':points}, 'global') }}
                </div>
                <div class="top"></div>
                {% if pictos|length == 0 %}
                <div class="list empty">
                    {{ 'Dieser Spieler hat bisher noch keine Preise gewonnen...'|trans({}, 'global') }}
                </div>
                {% else %}
                <div class"list">
                    {% for picto in pictos %}
                        <div class="picto{% if picto.rare %} rare{% endif %}">
                            <img src="{{  asset('build/images/pictos/' ~ picto.icon ~ '.gif') }}" /><br />
                            <div class="counter">
                            {% for number in picto.c|split('') %}<span class="count" title="{{number}}">{{number}}</span>{% endfor %}
                            </div>
                            <div class="tooltip">
                            <h1>{{ picto.label|trans({}, 'game') }}</h1>
                            {{ picto.description|trans({}, 'game')}}</em>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="distinctions-foot">
                &nbsp;
            </div>
        </div>
        <div class="cell padded rw-7 rw-sm-12">

            <div class="score"><img src="{{ asset('build/images/soul/small_score.gif') }}" alt="" /> {{ 'Seelenpunktzahl'|trans({}, 'global') }} : <strong>{{ '%points% Punkte'|trans({'%points%': app.user.soulPoints}, 'global') }}</strong></div>

            {% for incarnations in app.user.citizens %}
                {% if incarnations.alive %}
                    <div class="current">
                        <em>{{'Aktuelles Leben'|trans({}, 'global')}} : </em><br /><strong><img src="{{ asset('build/images/soul/r_explor.gif') }}" alt="" /> {{ incarnations.town.name }}</strong> ({{ 'Tag %day%'|trans({'%day%':incarnations.town.day}, 'game') }})
                    </div>
                {% set days = incarnations.survivedDays %}
                {% set nbSoulPoints = days * ( days + 1 ) / 2 %}
                {% endif %}
            {% endfor %}

            <div class="town-history">
                <div class="row header">
                    <div class="cell padded rw-2 center">
                        {{'Saison'|trans({}, 'global')}}
                    </div>
                    <div class="cell padded rw-6 center">
                        {{'Stadt'|trans({}, 'game')}}
                    </div>
                    <div class="cell padded rw-2 center">
                        {{'Tage'|trans({}, 'global')}}
                    </div>
                    <div class="cell padded rw-2 center">
                        {{'Punkte'|trans({}, 'global')}}
                    </div>
                </div>
                <div class="town-container">
                    {% for incarnation in app.user.citizens|filter(incarnation => not incarnation.alive)|sort((a,b) => a.survivedDays < b.survivedDays) %}
                        <div class="row{% if incarnation.town.type.name == 'panda' %} hardcore{% endif %}">
                        {% if not incarnation.alive %}
                            {% set days = incarnation.survivedDays %}
                            {% set nbSoulPoints = days * ( days + 1 ) / 2 %}
                                <div class="cell padded rw-2 center">
                                    {% if incarnation.town.season == null %}
                                    --
                                    {% else %}
                                        {{ incarnation.town.season.number }}
                                    {% endif %}
                                </div>
                                <div class="cell padded rw-6 center town-name">
                                    <div x-ajax-href="{{ path('soul_view_town', {id: incarnation.town.id}) }}">{% if incarnation.town.type.name == 'panda' %}<img src="{{ asset('build/images/soul/r_cannib.gif') }}" alt="" /> {% endif %}{{ incarnation.town.name }}</div>
                                    <div x-town-id="{{ incarnation.id }}" class="comment"><em>{% if not incarnation.comment is empty %}{{incarnation.comment}}{% else %}<span class="add-comment">{{'Einen Kommentar hinzufügen'|trans({}, 'soul')}}</span>{% endif %}</em></div>
                                </div>
                                <div class="cell padded rw-2 center town-days bold">
                                    {{ incarnation.survivedDays }}
                                    {% if incarnation.town.hasAliveCitizen %}
                                        <span>
                                            <img src="{{asset('build/images/small_new.gif')}}" />
                                            <div class="tooltip">
                                                {{ 'Es sind in dieser Stadt noch ein paar Bürger übrig...'|trans({}, 'soul') }}
                                            </div>
                                        </span>
                                    {% endif %}
                                </div>
                                <div class="cell padded rw-2 center town-points bold">
                                    +{{nbSoulPoints}}
                                </div>
                        </div>
                        {% endif %}
                    {% else %}
                        <div class="row">
                            <div class="empty">
                                {{'Es wurde keine Stadt gefunden...'|trans({}, 'global')}}
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    {{parent()}}
    <script>
        const send_build_request = function(id) {
            let comment = null;
            let valid = false;
            comment = window.prompt("{{ 'Was sagst du dazu?'|trans({},'game')|e('js') }}", "");
            if (comment === null) valid = false;
            else {
                valid = !(comment === "")
            }

            if (!valid) return;

            $.ajax.easySend( '{{ path('soul_add_comment') }}', {id: id, comment: comment},
                function () {
                    $.ajax.load(null, '{{ path('soul_me') }}', true);
            } );
        };

        let buttons = document.querySelectorAll('[x-town-id]');
        for (let i = 0; i < buttons.length; i++)
            buttons[i].addEventListener('click', function(e) { e.preventDefault(); e.stopPropagation(); send_build_request( this.getAttribute('x-town-id') ); })
    </script>
{% endblock %}

templates/ajax/soul/news.html.twig
{% extends "ajax/soul/shell.html.twig" %}
{% block menu_text %}
    {{ parent() }}
    {% if app.user and not app.user.activeCitizen %}
        <li class="town-dash" x-ajax-href="{{ url('ghost_welcome') }}">{% trans from 'global' %}Spiel{% endtrans %}</li>
    {% endif %}
{% endblock %}
{% block soul_content %}
    <div class="row">
        <div class="cell padded rw-12 rw-sm-12">
            COMING SOON.
        </div>
    </div>
{% endblock %}

templates/ajax/soul/rps.html.twig
{% extends "ajax/soul/shell.html.twig" %}
{% block soul_content %}
    <div class="row rp-head">
        <div class="cell padded rw-12 small center rp-context"><img alt="" src="{{ asset('build/images/small_rp.gif') }}" /> {{'Die Geschichte der Welt ist nichts anderes als die Summe mannigfaltiger Heldenerzählungen...'|trans({}, 'soul')}}</div>
        <div class="cell rw-8 center"><h5>{{'Titel'|trans({}, 'soul')}}</h5></div>
        <div class="cell rw-4 center"><h5>{{'Entdeckt'|trans({}, 'soul')}}</h5></div>
    </div>
    <div class="row rp-list">
        {% for rp in rps %}
        <div class="row rp-row" x-ajax-href="{{path('soul_rp', {id: rp.id, page: 1})}}">
            <div class="cell padded rw-8 rp-text">
                <span class="title">{{rp.text.title}}</span><br /><em>« {{rp.text.pages[0].content|striptags|slice(0,49)}}{% if rp.text.pages[0].content|striptags|length > 49 %}[...]{% endif %} »</em></div>
            <div class="cell padded rw-4 author">{{rp.datefound|date('d/m/Y H:i')}}</div>
        </div>
        {% endfor %}
        <div class="cell padded rw-12 center small">{{'Gefundene Texte: %count%'|trans({'%count%': rps|length}, "soul")}}</div>
    </div>
{% endblock %}

templates/ajax/soul/shell.html.twig
{% extends "ajax/ajax.html.twig" %}
{% block menu_text %}
    {{ parent() }}
{% endblock %}
{% block ajax %}
    <div class="row soul">
        <div class="cell padded header rw-10 ro-1 rw-md-12 ro-md-0">
            <div class="row tabs">
                <div class="cell-small rw-8 rw-lg-24">
                    {% if app.user.avatar %}
                        <div class="avatar small"><img alt="" src="{{ path('app_web_avatar', {'uid': app.user.id, 'name': app.user.avatar.smallName, 'ext': app.user.avatar.format}) }}"></div>
                    {% endif %}
                    <h4 class="soul-name">
                        <img src="{{ asset('build/images/small_ghost_red.gif') }}" alt="{{'Held'|trans({}, 'game')}}" /> {{ app.user.username }}
                    </h4>
                </div>
                <div class="cell-small rw-3 rw-lg-5 tab{% if soul_tab == "soul_me" %} selected{% endif %}">
                    <div class="tab-link" x-ajax-href="{{ path('soul_me') }}">{% trans from 'soul' %}Seele{% endtrans %}</div>
                </div>
                <div class="cell-small rw-3 rw-lg-5 tab{% if soul_tab == "soul_rps" %} selected{% endif %}">
                    <div class="tab-link" x-ajax-href="{{ path('soul_rps') }}">{% trans from 'soul' %}Schriften{% endtrans %}</div>
                </div>
                <div class="cell-small rw-3 rw-lg-5 tab{% if soul_tab == "soul_news" %} selected{% endif %}">
                    <div class="tab-link" x-ajax-href="{{ path('soul_news') }}">{% trans from 'soul' %}News{% endtrans %}</div>
                </div>
                <div class="cell-small rw-3 rw-lg-5 tab{% if soul_tab == "soul_settings" %} selected{% endif %}">
                    <div class="tab-link" x-ajax-href="{{ path('soul_settings') }}">{% trans from 'soul' %}Einstellungen{% endtrans %}</div>
                </div>
                <div class="cell rw-2 tab">
                    <a class="tab-link" target="_self" href="{{ path('auto_logout') }}">{% trans from 'soul' %}Logout{% endtrans %}</a>
                </div>
            </div>
            {% block soul_content %}
            {% endblock %}
        </div>
    </div>
{% endblock %}

templates/ajax/soul/view_rp.html.twig
{% extends "ajax/soul/shell.html.twig" %}
{% block soul_content %}
    <div class="row">
        <div class="cell padded rw-4">
            <button class='inline' x-ajax-href="{{path('soul_rps')}}"><img src="{{asset('build/images/soul/small_back.gif')}}" alt ="" /> {{'Zurück'|trans({}, 'global')}}</button>
        </div>
    </div>
    <div class="view-rp">
        <h5>{{rp.text.title}}</h5>
        {%if rp.text.pages|length > 1%}
        <div class="center"><span class="small">{{'Dieser Text hat mehrere Seiten. Klicke auf den Link, um zur nächsten Seite zu gelangen...'|trans({}, 'soul')}}</span></div>
        {% endif %}
        <div class="{{rp.text.background}}">
            <div class="rp-content design-{{rp.text.design}}" x-ajax-href="{%if rp.text.pages|length > 1 and current < rp.text.pages|length %}{{path('soul_rp', {id: rp.id, page: current+1})}}{% else %}{{ path('soul_rps') }}{% endif %}">
                {{page.content|raw}}
                </div>
            </div>
                {%if rp.text.pages|length > 1%}
                {% endif %}
            {%if rp.text.pages|length > 1 %}
            <div class="center">
                    <div class="cell padded pages center">{{'Seite %page%/%pages%'|trans({"%page%": current, "%pages%": rp.text.pages|length}, 'global')}}<br />
                {% if current > 1 %}
                    <button class="inline" x-ajax-href="{{path('soul_rp', {id: rp.id, page: current-1})}}"> {{'Vorherige Seite'|trans({}, 'soul')}}</button>
                {% endif %}
                {% if current < rp.text.pages|length %}
                    <button class="inline" x-ajax-href="{{path('soul_rp', {id: rp.id, page: current+1})}}"> {{'Nächste Seite'|trans({}, 'soul')}}</button>
                {% endif %}
            </div>
            {% endif %}
            <div class="right"><span class="author">{{'Redakteur:'|trans({}, 'soul')}} {{rp.text.author}}</span></div>
        </div>
    </div>
{% endblock %}

templates/ajax/soul/view_town.html.twig
{% extends "ajax/soul/shell.html.twig" %}
{% block soul_content %}
    <div class="row">
        <div class="cell padded rw-4">
            <button class='inline' x-ajax-href="{{path('soul_me')}}"><img src="{{asset('build/images/soul/small_back.gif')}}" alt ="" /> {{'Zurück'|trans({}, 'global')}}</button>
        </div>
    </div>
    <div class="view-town">
        <h5>{{town.name}}</h5>
        <div class="row-table citizens-list">
            <div class="row header">
                <div class="padded cell rw-2">{{'Überlebte Tage'|trans({}, 'soul')}}</div>
                <div class="padded cell rw-1">{{'Ergebnis'|trans({}, 'soul')}}</div>
                <div class="padded cell rw-2">{{'Bürger'|trans({}, 'soul')}}</div>
                <div class="padded cell rw-4">{{'Todesursache'|trans({}, 'soul')}}</div>
                <div class="padded cell rw-3">{{'Kommentar'|trans({}, 'soul')}}</div>
            </div>
            {% for citizen in town.citizens|filter(c => not c.alive)|sort((a,b) => b.survivedDays <=> a.survivedDays) %}
                {% set days = citizen.survivedDays %}
                {% set sp = days * ( days + 1 ) / 2 %}
            <div class="row">
                <div class="padded cell rw-2">{{citizen.survivedDays}}</div>
                <div class="padded cell rw-1 town-points bold">+{{sp}}</div>
                <div class="padded cell rw-2">{{citizen.user.username}}</div>
                <div class="padded cell rw-4">
                    {{citizen.causeOfDeath.label|trans({}, 'game')}}
                    {% if not citizen.lastWords is empty %}
                    <img src="{{asset('build/images/log/chat.gif')}}" />
                    {% endif %}
                    <div class="tooltip">
                        {% if citizen.lastWords is empty %}
                            <span>{{ 'Dieser Bürger hat keine letzten Worte hinterlassen ...'|trans({}, 'game') }}</span>
                        {% else %}
                            <b>{{"Letzte Worte:"|trans({}, 'game')}}</b> {{ citizen.lastWords }}
                        {% endif %}
                    </div>
                </div>
                <div class="padded cell rw-3 comment">{{citizen.comment}}</div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}