src/Entity/Town.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\OrderBy;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TownRepository")
 */
class Town
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=190)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=8)
     */
    private $language;

    /**
     * @ORM\Column(type="integer")
     */
    private $population;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $wordsOfHeroes;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Citizen", mappedBy="town", orphanRemoval=true, cascade={"persist", "remove"})
     * @OrderBy({"alive" = "DESC", "id" = "ASC"})
     */
    private $citizens;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Inventory", inversedBy="town", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $bank;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\TownClass", inversedBy="towns")
     * @ORM\JoinColumn(nullable=false)
     */
    private $type;

    /**
     * @ORM\Column(type="integer")
     */
    private $day = 1;

    /**
     * @ORM\Column(type="integer")
     */
    private $well;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Zone", mappedBy="town", orphanRemoval=true, cascade={"persist", "remove"})
     */
    private $zones;

    /**
     * @ORM\Column(type="boolean")
     */
    private $door = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $chaos = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $devastated = false;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Building", mappedBy="town", orphanRemoval=true, cascade={"persist", "remove"})
     * @ORM\OrderBy({"position" = "ASC"})
     */
    private $buildings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ZombieEstimation", mappedBy="town", orphanRemoval=true, cascade={"persist"})
     */
    private $zombieEstimations;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Forum", mappedBy="town", cascade={"persist", "remove"})
     */
    private $forum;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $conf = [];

    /**
     * @ORM\Column(type="integer")
     */
    private $soulDefense = 0;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Season", inversedBy="towns")
     */
    private $season;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CitizenWatch", mappedBy="town", orphanRemoval=true)
     */
    private $citizenWatches;

    public function __construct()
    {
        $this->citizens = new ArrayCollection();
        $this->zones = new ArrayCollection();
        $this->buildings = new ArrayCollection();
        $this->zombieEstimations = new ArrayCollection();
        $this->citizenWatches = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLanguage(): ?string
    {
        return $this->language;
    }

    public function setLanguage(string $language): self
    {
        $this->language = $language;

        return $this;
    }

    public function getWordsOfHeroes(): ?string
    {
        return $this->wordsOfHeroes;
    }

    public function setWordsOfHeroes(string $wordsOfHeroes): self
    {
        $this->wordsOfHeroes = $wordsOfHeroes;

        return $this;
    }

    public function getPopulation(): ?int
    {
        return $this->population;
    }

    public function setPopulation(int $population): self
    {
        $this->population = $population;

        return $this;
    }

    public function getCitizenCount(): int {
        return count($this->getCitizens());
    }

    public function isOpen(): bool {
        return $this->getDay() === 1 && $this->getCitizenCount() < $this->getPopulation();
    }

    /**
     * @return Collection|Citizen[]
     */
    public function getCitizens(): Collection
    {
        return $this->citizens;
    }

    public function addCitizen(Citizen $citizen): self
    {
        if (!$this->citizens->contains($citizen)) {
            $this->citizens[] = $citizen;
            $citizen->setTown($this);
        }

        return $this;
    }

    public function removeCitizen(Citizen $citizen): self
    {
        if ($this->citizens->contains($citizen)) {
            $this->citizens->removeElement($citizen);
            // set the owning side to null (unless already changed)
            if ($citizen->getTown() === $this) {
                $citizen->setTown(null);
            }
        }

        return $this;
    }

    public function getBank(): ?Inventory
    {
        return $this->bank;
    }

    public function setBank(Inventory $bank): self
    {
        $this->bank = $bank;

        return $this;
    }

    public function getType(): ?TownClass
    {
        return $this->type;
    }

    public function setType(?TownClass $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDay(): ?int
    {
        return $this->day;
    }

    public function setDay(int $day): self
    {
        $this->day = $day;

        return $this;
    }

    public function getWell(): ?int
    {
        return $this->well;
    }

    public function setWell(int $well): self
    {
        $this->well = $well;

        return $this;
    }

    /**
     * @return Collection|Zone[]
     */
    public function getZones(): Collection
    {
        return $this->zones;
    }

    public function addZone(Zone $zone): self
    {
        if (!$this->zones->contains($zone)) {
            $this->zones[] = $zone;
            $zone->setTown($this);
        }

        return $this;
    }

    public function removeZone(Zone $zone): self
    {
        if ($this->zones->contains($zone)) {
            $this->zones->removeElement($zone);
            // set the owning side to null (unless already changed)
            if ($zone->getTown() === $this) {
                $zone->setTown(null);
            }
        }

        return $this;
    }

    public function getDoor(): ?bool
    {
        return $this->door;
    }

    public function setDoor(bool $door): self
    {
        $this->door = $door;

        return $this;
    }

    public function getChaos(): ?bool
    {
        return $this->chaos;
    }

    public function setChaos(bool $chaos): self
    {
        $this->chaos = $chaos;

        return $this;
    }


    public function getForum(): ?Forum
    {
        return $this->forum;
    }

    public function setForum(?Forum $forum): self
    {
        $this->forum = $forum;

        // set (or unset) the owning side of the relation if necessary
        $newTown = null === $forum ? null : $this;
        if ($forum->getTown() !== $newTown) {
            $forum->setTown($newTown);
        }

        return $this;
    }

    public function getDevastated(): ?bool
    {
        return $this->devastated;
    }

    public function setDevastated(bool $devastated): self
    {
        $this->devastated = $devastated;

        return $this;
    }

    /**
     * @return Collection|Building[]
     */
    public function getBuildings(): Collection
    {
        return $this->buildings;
    }

    public function addBuilding(Building $building): self
    {
        if (!$this->buildings->contains($building)) {
            $this->buildings[] = $building;
            $building->setTown($this);
        }

        return $this;
    }

    public function removeBuilding(Building $building): self
    {
        if ($this->buildings->contains($building)) {
            $this->buildings->removeElement($building);
            // set the owning side to null (unless already changed)
            if ($building->getTown() === $this) {
                $building->setTown(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ZombieEstimation[]
     */
    public function getZombieEstimations(): Collection
    {
        return $this->zombieEstimations;
    }

    public function addZombieEstimation(ZombieEstimation $zombieEstimation): self
    {
        if (!$this->zombieEstimations->contains($zombieEstimation)) {
            $this->zombieEstimations[] = $zombieEstimation;
            $zombieEstimation->setTown($this);
        }

        return $this;
    }

    public function removeZombieEstimation(ZombieEstimation $zombieEstimation): self
    {
        if ($this->zombieEstimations->contains($zombieEstimation)) {
            $this->zombieEstimations->removeElement($zombieEstimation);
            // set the owning side to null (unless already changed)
            if ($zombieEstimation->getTown() === $this) {
                $zombieEstimation->setTown(null);
            }
        }

        return $this;
    }

    public function getConf(): ?array
    {
        return $this->conf;
    }

    public function setConf(?array $conf): self
    {
        $this->conf = $conf;

        return $this;
    }

    public function getSoulDefense(): ?int
    {
        return $this->soulDefense;
    }

    public function setSoulDefense(int $soulDefense): self
    {
        $this->soulDefense = $soulDefense;

        return $this;
    }

    public function getSeason(): ?Season
    {
        return $this->season;
    }

    public function setSeason(?Season $season): self
    {
        $this->season = $season;

        return $this;
    }

    public function hasAliveCitizen(): bool
    {
        foreach ($this->getCitizens() as $citizen) {
            if($citizen->getAlive())

templates/ajax/game/actions.html.twig
{% if scout is not defined %}
    {% set scout = false %}
{% endif %}
{% if hidden is not defined %}
    {% set hidden = false %}
{% endif %}

{% if not hidden %}
    {% macro target_popup( action_id, provoking_id, targets, target_for, text_having, text_missing, close_button = false, big = false ) %}
        <div class="targets" x-target-selection-for="{{ target_for }}">
            {% if targets|length > 0 %}
                <span>{{ text_having }}</span>
                <ul>
                    {% for target in targets %}
                        {# @var item \App\Entity\Item #}
                        <li x-action-id="{{ action_id }}" {% if provoking_id is not null %}x-provoking-id="{{ provoking_id }}"{% endif %} x-target-id="{{ target[0] }}" >
                            {% if big %}
                                <div><img src="{{ asset(target[2]) }}" alt="{{ target[1] }}"> {{ target[1] }}</div>
                            {% else %}
                                <img src="{{ asset(target[2]) }}" alt="{{ target[1] }}">
                            {% endif %}

                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <span>{{ text_missing }}</span>
            {% endif %}
            {% if close_button %}
                <div class="right"><span x-close-for="{{ target_for }}">{{ 'Schließen'|trans({},'global') }}</span></div>
            {% endif %}
        </div>
    {% endmacro %}

    {% if (item_action_list is defined and item_action_list|length > 0) or (recipe_list is defined and recipe_list.recipes|length > 0)  %}
        <ul class="actions">
            {% if (item_action_list is defined) %}
                {% for entry in item_action_list %}
                    <li class="action" {% if entry.crossed %}disabled{% elseif entry.targets is null %}x-action-id="{{ entry.id }}" x-provoking-id="{{ entry.item.id }}"{% else %}x-target-definition="{{ entry.id }}--{{ entry.item.id }}"{% endif %}>
                        <img src="{{ asset('build/images/item/item_' ~ entry.item.prototype.icon ~ '.gif') }}" alt="{{ entry.item.prototype.label|trans({},'items') }}">
                        {% if scout and not entry.action.keepsCover %}
                            <img class="float-right" src="{{ asset('build/images/uncloak.gif') }}" alt="">
                        {% endif %}
                        <span>{{ '%action%: %item%'|trans({'%action%': entry.action.label|trans({},'items')|e('html'), '%item%': '<b>' ~ entry.item.prototype.label|trans({},'items')|e('html') ~ '</b>'},'items')|raw }}</span>
                        {% if entry.targets is not null and not entry.crossed %}
                            {% if entry.target_mode == 2 %}
                                {{ _self.target_popup( entry.id, entry.item.id, entry.targets, entry.id ~ '--' ~ entry.item.id, 'Bitte wähle einen Bürger:'|trans({},'game'), 'Es ist kein Bürger in der Nähe...'|trans({},'game'), true, true ) }}
                            {% else %}
                                {{ _self.target_popup( entry.id, entry.item.id, entry.targets, entry.id ~ '--' ~ entry.item.id, 'Bitte wähle einen Gegenstand:'|trans({},'game'), 'Du verfügst über keine geeigneten Gegenstände'|trans({},'game'), true, false ) }}
                            {% endif %}
                        {% endif %}
                    </li>
                {% endfor %}
            {% endif %}
            {% if recipe_list is defined %}
                {% for recipe in recipe_list.recipes %}
                    <li class="action" x-recipe-id="{{ recipe.id }}">
                        {# @var recipe \App\Entity\Recipe #}
                        {% if recipe.result.entries.count == 1 %}
                            {% if scout %}
                                <img class="float-right" src="{{ asset('build/images/uncloak.gif') }}" alt="">
                            {% endif %}
                            {% if recipe.source and not conf.get(constant('App\\Structures\\TownConf::CONF_MODIFIER_PRE_ASSEMBLY'),false) %}
                                <span>{{ 'Zusammenbauen'|trans({},'game') }}:
                                    {% for entry in recipe.source.entries %}
                                        {# @var entry \App\Entity\ItemGroupEntry #}
                                        {% for n in 1..entry.chance %}
                                            <img class="{% if n > recipe_list.source_items[entry.prototype.id] %}unavailable{% endif %}" src="{{ asset('build/images/item/item_' ~ entry.prototype.icon ~ '.gif') }}" alt="{{ entry.prototype.label|trans({},'items') }}">
                                        {% endfor %}
                                    {% endfor %}
                                </span>
                            {% else %}
                                <img src="{{ asset('build/images/item/item_' ~ recipe.result.entries[0].prototype.icon ~ '.gif') }}" alt="{{ recipe.result.entries[0].prototype.label|trans({},'items') }}">
                                <span>{{ 'Herstellen'|trans({},'game') }}: <b>{{ recipe.result.entries[0].prototype.label|trans({},'items') }}</b></span>
                                {% if recipe.source %}
                                    <span>
                                    {{ 'aus'|trans({},'game') }}:
                                    {% for entry in recipe.source.entries %}
                                        {# @var entry \App\Entity\ItemGroupEntry #}
                                        {% for n in 1..entry.chance %}
                                            <img class="{% if n > recipe_list.source_items[entry.prototype.id] %}unavailable{% endif %}" src="{{ asset('build/images/item/item_' ~ entry.prototype.icon ~ '.gif') }}" alt="{{ entry.prototype.label|trans({},'items') }}">
                                        {% endfor %}
                                    {% endfor %}
                                </span>
                                {% endif %}
                            {% endif %}

                        {% else %}
                            {% if recipe.source %}
                                {% if scout %}
                                    <img class="float-right" src="{{ asset('build/images/uncloak.gif') }}" alt="">
                                {% endif %}
                                <span>
                                    {{ 'Kombinieren'|trans({},'game') }}:
                                    {% for entry in recipe.source.entries %}
                                        {# @var entry \App\Entity\ItemGroupEntry #}
                                        {% for n in 1..entry.chance %}
                                            <img class="{% if n > recipe_list.source_items[entry.prototype.id] %}unavailable{% endif %}" src="{{ asset('build/images/item/item_' ~ entry.prototype.icon ~ '.gif') }}" alt="{{ entry.prototype.label|trans({},'items') }}">
                                        {% endfor %}
                                    {% endfor %}
                                </span>
                            {% endif %}
                        {% endif %}
                    </li>
                {% endfor %}
            {% endif %}
        </ul>
    {% endif %}

    {% if special_action_list is defined and special_action_list|length > 0 %}
        <ul class="special_actions">
            {% for entry in special_action_list %}
                <li class="heroic_action" {% if entry.crossed %}disabled{% elseif entry.targets is null %}x-action-id="{{ entry.id }}"{% else %}x-target-definition="{{ entry.id }}--special"{% endif %}>
                    <img src="{{ asset('build/images/actions/' ~ entry.icon ~ '.gif') }}" alt="">
                    <span><b>{{ entry.action.label|trans({},'items') }}</b></span>
                    {% if entry.targets is not null and not entry.crossed %}
                        {% if entry.target_mode == 2 %}
                            {{ _self.target_popup( entry.id, null, entry.targets, entry.id ~ '--special', 'Bitte wähle einen Bürger:'|trans({},'game'), 'Es ist kein Bürger in der Nähe...'|trans({},'game'), true, true ) }}
                        {% else %}
                            {{ _self.target_popup( entry.id, null, entry.targets, entry.id ~ '--special', 'Bitte wähle einen Gegenstand:'|trans({},'game'), 'Du verfügst über keine geeigneten Gegenstände'|trans({},'game'), true, false ) }}
                        {% endif %}
                    {% endif %}
                </li>
            {% endfor %}
        </ul>

    {% endif %}

    {% if heroic_action_list is defined and heroic_action_list|length > 0 %}
        <button x-heroic-toggle="1"><img src="{{ asset('build/images/star.gif') }}" alt="">{{ 'Heldentaten'|trans({},'items')  }}</button>
        <ul class="heroic_actions">
            {% for entry in heroic_action_list %}
                <li class="heroic_action" {% if entry.crossed %}disabled{% elseif entry.targets is null %}x-action-id="{{ entry.id }}"{% else %}x-target-definition="{{ entry.id }}--hero"{% endif %}>
                    <img src="{{ asset('build/images/star.gif') }}" alt="">
                    {% if scout and not entry.action.keepsCover %}
                        <img class="float-right" src="{{ asset('build/images/uncloak.gif') }}" alt="">
                    {% endif %}
                    <span><b>{{ entry.action.label|trans({},'items') }}</b></span>
                    {% if entry.targets is not null and not entry.crossed %}
                        {% if entry.target_mode == 2 %}
                            {{ _self.target_popup( entry.id, null, entry.targets, entry.id ~ '--hero', 'Bitte wähle einen Bürger:'|trans({},'game'), 'Es ist kein Bürger in der Nähe...'|trans({},'game'), true, true ) }}
                        {% else %}
                            {{ _self.target_popup( entry.id, null, entry.targets, entry.id ~ '--hero', 'Bitte wähle einen Gegenstand:'|trans({},'game'), 'Du verfügst über keine geeigneten Gegenstände'|trans({},'game'), true, false ) }}
                        {% endif %}
                    {% endif %}
                </li>
            {% endfor %}
            <li><div class="right pointer small" x-heroic-toggle="0">{{ 'Schließen'|trans({},'global') }}</div></li>
        </ul>

    {% endif %}
{% else %}
    <ul class="actions">
        <li>{{ 'Du kannst keine Aktionen ausführen, während du dich versteckst.'|trans({},'game')  }}</li>
    </ul>
{% endif %}

templates/ajax/game/camping.html.twig
{% if scout is not defined %}
    {% set scout = false %}
{% endif %}

{% if list|length > 0  %}
    <ul class="camping_actions">
        {% for entry in list %}
            <li class="camping_action" {% if entry.crossed %}disabled="disabled"{% else %}x-action-id="{{ entry.action.id }}"{% endif %}>
                {% if entry.action.action.name == 'campsite_improve' %}
                    <img src="{{ asset('build/images/small_refine.gif') }}" alt="">
                {% else %}
                    <img src="{{ asset('build/images/status/status_camper.gif') }}" alt="">
                {% endif %}
                <span>{{ entry.action.action.label|trans({},'items') }}</span>
            </li>
        {% endfor %}

    </ul>
{% endif %}

templates/ajax/game/inventory.html.twig
{% if escort is not defined %}
    {% set escort = null %}
{% endif %}
{% if bankmode is defined and bankmode %}
    <input type="text" name="banksearch" id="banksearch" placeholder="{{ 'Gegenstände suchen'|trans({},'items') }}"/>
{% endif %}
<ul {% if bankmode is defined and bankmode %}id="bank-inventory"{% endif %} class="inventory {% block class %}{% endblock %}">
    {% if bankmode is not defined or not bankmode %}
        <li class="title">{% block title %}{% endblock %}</li>
        {% for item in items %}
            {% embed "ajax/game/item.html.twig" with {'item': item, 'escort': escort} %}{% endembed %}
        {% endfor %}
        {% if items|length < size %}
            {% for i in range(0, size - items|length - 1) %}
                <li class="free"></li>
            {% endfor %}
        {% endif %}
        {% if plus is defined and plus %}
            <li class="item plus" {% if escort is not null%}x-escort-id="{{ escort }}"{% endif%} ><img alt="+" src="{{ asset('build/images/small_more.gif') }}" /></li>
        {% endif %}
    {% else %}
        {% for category,list in items %}
            <li class="category">{{ category|trans({},'items') }}</li>
            {% for entry in list %}
                {% embed "ajax/game/item.html.twig" with {'item': entry.item, 'count': entry.count} %}{% endembed %}
            {% endfor %}
        {% endfor %}

    {% endif %}
</ul>

templates/ajax/game/item.html.twig
{# @var item \App\Entity\Item #}
{% set classes = ['item'] %}
{% if item.broken %}{% set classes = classes|merge(['broken']) %}{% endif %}
{% if count is defined and count > 1 %}{% set classes = classes|merge(['counted']) %}{% endif %}

<li class="{{ classes|join(' ') }}" {% if no_id is not defined or not no_id %}x-item-id="{{ item.id }}"{% endif %} {% if escort is defined and escort is not null %}x-escort-id="{{ escort }}"{% endif %}>
    <img src="{{ asset('build/images/item/item_' ~ item.prototype.icon ~ '.gif') }}" alt="{{ item.prototype.label|trans({},'items') }}">
    {% if count is defined and count > 1 %}<span>{{ count }}</span>{% endif %}
    {% if no_tooltip is not defined or not no_tooltip %}
        <div class="tooltip">
            <h1>{{ item.prototype.label|trans({},'items') }} <span class="broken">{% if item.broken %}({{ 'Kaputt'|trans({},'items') }})</span>{% endif %}</h1>
            {{ item.prototype.description|trans({},'items') }}
            {% if item.essential %}<div class="item-tag item-tag-essential">{{ 'Berufsgegenstand'|trans({},'items') }}</div>{% endif %}
            {% if item.prototype.heavy %}<div class="item-tag item-tag-heavy">{{ 'Schwerer Gegenstand'|trans({},'items') }}</div>{% endif %}
            {% if item.prototype.deco > 0 %}<div class="item-tag item-tag-deco">{{ 'Einrichtungsgegenstand'|trans({},'items') }}</div>{% endif %}
            {% if item.prototype.hasProperty('defence') %}<div class="item-tag item-tag-defense">{{ 'Verteidigungsgegenstand'|trans({},'items') }}</div>{% endif %}
            {% if item.prototype.hasProperty('weapon') %}<div class="item-tag item-tag-weapon">{{ 'Waffe'|trans({},'items') }}</div>{% endif %}
            {% if item.prototype.watchpoint > 0 %}<div class="item-tag item-tag-weapon">{{ 'Nachtwache-Waffen'|trans({},'items') }} <em>({{item.prototype.watchpoint}} {{ 'Pkte'|trans({},'items') }})</em></div>{% endif %}
        </div>
    {% endif %}
</li>

templates/ajax/game/log_content.html.twig
{# @var entries \App\Entity\TownLogEntry[] #}
{% if entries|length == 0 %}
    <i>{{ 'Heute ist nichts Erwähnenswertes passiert...'|trans({},'game') }}</i>
{% else %}
    {% for entry in entries %}
        <div class="log-entry log-entry-type-{{ entry.type }} log-entry-class-{{ entry.class }}">
            <span class="log-part-time">{{ entry.timestamp.format('G:i') }}</span>
            <span class="log-part-content">{{ entry.text|raw }}</span>
        </div>
    {% endfor %}
{% endif %}

templates/ajax/game/newspaper.html.twig
{% extends "ajax/game/game.html.twig" %}
{% block menu_text %}
    {{ parent() }}
    {% if show_town_link %}
        <li class="town-dash" x-ajax-href="{{ url('town_dashboard') }}">{% trans from 'game' %}Stadt{% endtrans %}</li>
    {% else %}
        <li class="beyond-dash" x-ajax-href="{{ url('beyond_dashboard') }}">{% trans from 'game' %}Zone{% endtrans %}</li>
    {% endif %}
{% endblock %}
{% block ajax %}
    {{ parent() }}
    <div class="row">

        <div class="padded cell rw-12">

            <input type="checkbox" name="gazette-switch" id="gazette-switch" />
            <div id="gazette">
                <div id="newspage-front" class="newspage">
                    <div id="gazette-headline">
                        {{ gazette.name }} ({{ gazette.day }})
                    </div>
                    <div id="gazette-content" class="{{gazette.textClass}}">
                        {{gazette.text|raw}}
                    </div>
                    <div id="gazette-signature">
                        - {{'Der Rabe'|trans({}, 'global')}}
                    </div>
                    {% if gazette.day > 1 %}
                        <div id="gazette-deaths">
                            <div id="gazette-death-inside" class="death">
                                <div class="death-category">
                                    {{'Tote in der Stadt'|trans({}, 'game')}} {% if gazette.death_inside|length > 0 %}({{ gazette.death_inside|length }}){% endif %}:
                                </div>
                                {% if gazette.death_inside|length == 0 %}
                                    {{'Niemand!'|trans({}, 'game')}}
                                {% else %}
                                    {% for citizen in gazette.death_inside %}
                                        <span>
                                        {{citizen.user.username}}
                                        <div class="tooltip">
                                            {{citizen.causeOfDeath.label|trans({}, 'game')}}
                                        </div>
                                    </span>
                                    {% endfor %}
                                {% endif %}
                            </div>
                            {% if gazette.death_outside|length > 0 %}
                                <div id="gazette-death-outside" class="death">
                                    <div class="death-category">
                                        {{'Sonstige Opfer'|trans({}, 'game')}} ({{ gazette.death_outside|length }}):
                                    </div>
                                    {% for citizen in gazette.death_outside %}
                                        <span>
                                        {{citizen.user.username}}
                                        <div class="tooltip">
                                            {{citizen.causeOfDeath.label|trans({}, 'game')}}
                                        </div>
                                    </span>
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                    {% endif %}
                    {% if not gazette.open %}
                        <div id="gazette-tally">
                            {% if gazette.days.repeat > 0 %}
                                {% for i in 1..gazette.days.repeat %}
                                    {% set v = (i % 3) + 1 %}
                                    <div class="tally tally-5-{{ v }}"></div>
                                {% endfor %}
                            {% endif %}
                            {% if gazette.days.final > 0 %}
                                <div class="tally tally-{{ gazette.days.final }}"></div>
                            {% endif %}
                        </div>
                    {% endif %}
                </div>
                <div id="newspage-back" class="newspage">
                    {% if gazette.day > 1 %}
                        <div id="gazette-attack" class="row {% if gazette.devast %}devast{% endif %}">
                            <div class="nightstat nightstat-attack"><span class="count">{{ gazette.attack }}</span>
                                {{ 'Zombies'|trans({},'game') }}</div>
                            <div class="nightstat nightstat-defense"><span class="count">{{ gazette.defense }}</span>
                                {{ 'Verteidigung'|trans({},'game') }}</div>
                            <div class="nightstat nightstat-deaths">{% if gazette.deaths > 0 %}<span class="count">{{ gazette.deaths }}</span> {{ 'Opfer'|trans }}{% else %}<span class="count">{{ 'Keine Opfer'|trans({},'game') }}</span>{% endif %}</div>
                        </div>
                    {% else %}
                        <div id="gazette-empty"></div>
                    {% endif %}
                </div>
            </div>
            <div id="gazette-switcher"><label class="button" for="gazette-switch">{{ 'Umdrehen'|trans }}</label></div>

            <h5>{{ 'Stadtregister'|trans({},'game') }}</h5>
            {% if show_register %}
                {% embed "ajax/game/log.html.twig" with {'log_content': log, 'log_source': path('game_newspaper_log_controller') } %}
                {% endembed %}
            {% else %}
            <div class="note">
                {% trans from 'game' %}
                    Das Stadtregister steht nicht zur Verfügung.
                {% endtrans %}
            </div>
            {% endif %}
        </div>
    </div>
{% endblock %}
{% block js %}
    {{ parent() }}
    <script>
        {% if show_register %}
            {% embed "scripts/log.js.twig" %}{% endembed %}
        {% endif %}
    </script>
{% endblock %}